/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CockpitRouteImport } from './routes/cockpit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuraRouteImport } from './routes/aura'
import { Route as AnalysesPartageesRouteImport } from './routes/analyses-partagees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuraIndexRouteImport } from './routes/aura.index'
import { Route as CockpitUtilisateursRouteImport } from './routes/cockpit.utilisateurs'
import { Route as CockpitStudioRouteImport } from './routes/cockpit.studio'
import { Route as CockpitResilienceRouteImport } from './routes/cockpit.resilience'
import { Route as CockpitHomeRouteImport } from './routes/cockpit.home'
import { Route as CockpitEnergieRouteImport } from './routes/cockpit.energie'
import { Route as CockpitDemosRouteImport } from './routes/cockpit.demos'
import { Route as CockpitComptesRouteImport } from './routes/cockpit.comptes'
import { Route as CockpitCasReferencesRouteImport } from './routes/cockpit.cas-references'
import { Route as CockpitAtelierRouteImport } from './routes/cockpit.atelier'
import { Route as CockpitAdminPlateformeRouteImport } from './routes/cockpit.admin-plateforme'
import { Route as CockpitAbonnementRouteImport } from './routes/cockpit.abonnement'
import { Route as AvisTokenRouteImport } from './routes/avis.$token'
import { Route as AuraTarifsRouteImport } from './routes/aura.tarifs'
import { Route as AuraSolutionsRouteImport } from './routes/aura.solutions'
import { Route as AuraScienceRouteImport } from './routes/aura.science'
import { Route as AuraPlateformeRouteImport } from './routes/aura.plateforme'
import { Route as AuraMethodeRouteImport } from './routes/aura.methode'
import { Route as ApiIntegrationCronRouteImport } from './routes/api/integration/cron'
import { Route as ApiAuraDialogueRouteImport } from './routes/api/aura/dialogue'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const CockpitRoute = CockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraRoute = AuraRouteImport.update({
  id: '/aura',
  path: '/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesPartageesRoute = AnalysesPartageesRouteImport.update({
  id: '/analyses-partagees',
  path: '/analyses-partagees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraIndexRoute = AuraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuraRoute,
} as any)
const CockpitUtilisateursRoute = CockpitUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitStudioRoute = CockpitStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitResilienceRoute = CockpitResilienceRouteImport.update({
  id: '/resilience',
  path: '/resilience',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitHomeRoute = CockpitHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitEnergieRoute = CockpitEnergieRouteImport.update({
  id: '/energie',
  path: '/energie',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitDemosRoute = CockpitDemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitComptesRoute = CockpitComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitCasReferencesRoute = CockpitCasReferencesRouteImport.update({
  id: '/cas-references',
  path: '/cas-references',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitAtelierRoute = CockpitAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitAdminPlateformeRoute = CockpitAdminPlateformeRouteImport.update({
  id: '/admin-plateforme',
  path: '/admin-plateforme',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitAbonnementRoute = CockpitAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => CockpitRoute,
} as any)
const AvisTokenRoute = AvisTokenRouteImport.update({
  id: '/avis/$token',
  path: '/avis/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraTarifsRoute = AuraTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => AuraRoute,
} as any)
const AuraSolutionsRoute = AuraSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => AuraRoute,
} as any)
const AuraScienceRoute = AuraScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => AuraRoute,
} as any)
const AuraPlateformeRoute = AuraPlateformeRouteImport.update({
  id: '/plateforme',
  path: '/plateforme',
  getParentRoute: () => AuraRoute,
} as any)
const AuraMethodeRoute = AuraMethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => AuraRoute,
} as any)
const ApiIntegrationCronRoute = ApiIntegrationCronRouteImport.update({
  id: '/api/integration/cron',
  path: '/api/integration/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuraDialogueRoute = ApiAuraDialogueRouteImport.update({
  id: '/api/aura/dialogue',
  path: '/api/aura/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses-partagees': typeof AnalysesPartageesRoute
  '/aura': typeof AuraRouteWithChildren
  '/auth': typeof AuthRoute
  '/cockpit': typeof CockpitRouteWithChildren
  '/aura/methode': typeof AuraMethodeRoute
  '/aura/plateforme': typeof AuraPlateformeRoute
  '/aura/science': typeof AuraScienceRoute
  '/aura/solutions': typeof AuraSolutionsRoute
  '/aura/tarifs': typeof AuraTarifsRoute
  '/avis/$token': typeof AvisTokenRoute
  '/cockpit/abonnement': typeof CockpitAbonnementRoute
  '/cockpit/admin-plateforme': typeof CockpitAdminPlateformeRoute
  '/cockpit/atelier': typeof CockpitAtelierRoute
  '/cockpit/cas-references': typeof CockpitCasReferencesRoute
  '/cockpit/comptes': typeof CockpitComptesRoute
  '/cockpit/demos': typeof CockpitDemosRoute
  '/cockpit/energie': typeof CockpitEnergieRoute
  '/cockpit/home': typeof CockpitHomeRoute
  '/cockpit/resilience': typeof CockpitResilienceRoute
  '/cockpit/studio': typeof CockpitStudioRoute
  '/cockpit/utilisateurs': typeof CockpitUtilisateursRoute
  '/aura/': typeof AuraIndexRoute
  '/api/aura/dialogue': typeof ApiAuraDialogueRoute
  '/api/integration/cron': typeof ApiIntegrationCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses-partagees': typeof AnalysesPartageesRoute
  '/auth': typeof AuthRoute
  '/cockpit': typeof CockpitRouteWithChildren
  '/aura/methode': typeof AuraMethodeRoute
  '/aura/plateforme': typeof AuraPlateformeRoute
  '/aura/science': typeof AuraScienceRoute
  '/aura/solutions': typeof AuraSolutionsRoute
  '/aura/tarifs': typeof AuraTarifsRoute
  '/avis/$token': typeof AvisTokenRoute
  '/cockpit/abonnement': typeof CockpitAbonnementRoute
  '/cockpit/admin-plateforme': typeof CockpitAdminPlateformeRoute
  '/cockpit/atelier': typeof CockpitAtelierRoute
  '/cockpit/cas-references': typeof CockpitCasReferencesRoute
  '/cockpit/comptes': typeof CockpitComptesRoute
  '/cockpit/demos': typeof CockpitDemosRoute
  '/cockpit/energie': typeof CockpitEnergieRoute
  '/cockpit/home': typeof CockpitHomeRoute
  '/cockpit/resilience': typeof CockpitResilienceRoute
  '/cockpit/studio': typeof CockpitStudioRoute
  '/cockpit/utilisateurs': typeof CockpitUtilisateursRoute
  '/aura': typeof AuraIndexRoute
  '/api/aura/dialogue': typeof ApiAuraDialogueRoute
  '/api/integration/cron': typeof ApiIntegrationCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses-partagees': typeof AnalysesPartageesRoute
  '/aura': typeof AuraRouteWithChildren
  '/auth': typeof AuthRoute
  '/cockpit': typeof CockpitRouteWithChildren
  '/aura/methode': typeof AuraMethodeRoute
  '/aura/plateforme': typeof AuraPlateformeRoute
  '/aura/science': typeof AuraScienceRoute
  '/aura/solutions': typeof AuraSolutionsRoute
  '/aura/tarifs': typeof AuraTarifsRoute
  '/avis/$token': typeof AvisTokenRoute
  '/cockpit/abonnement': typeof CockpitAbonnementRoute
  '/cockpit/admin-plateforme': typeof CockpitAdminPlateformeRoute
  '/cockpit/atelier': typeof CockpitAtelierRoute
  '/cockpit/cas-references': typeof CockpitCasReferencesRoute
  '/cockpit/comptes': typeof CockpitComptesRoute
  '/cockpit/demos': typeof CockpitDemosRoute
  '/cockpit/energie': typeof CockpitEnergieRoute
  '/cockpit/home': typeof CockpitHomeRoute
  '/cockpit/resilience': typeof CockpitResilienceRoute
  '/cockpit/studio': typeof CockpitStudioRoute
  '/cockpit/utilisateurs': typeof CockpitUtilisateursRoute
  '/aura/': typeof AuraIndexRoute
  '/api/aura/dialogue': typeof ApiAuraDialogueRoute
  '/api/integration/cron': typeof ApiIntegrationCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses-partagees'
    | '/aura'
    | '/auth'
    | '/cockpit'
    | '/aura/methode'
    | '/aura/plateforme'
    | '/aura/science'
    | '/aura/solutions'
    | '/aura/tarifs'
    | '/avis/$token'
    | '/cockpit/abonnement'
    | '/cockpit/admin-plateforme'
    | '/cockpit/atelier'
    | '/cockpit/cas-references'
    | '/cockpit/comptes'
    | '/cockpit/demos'
    | '/cockpit/energie'
    | '/cockpit/home'
    | '/cockpit/resilience'
    | '/cockpit/studio'
    | '/cockpit/utilisateurs'
    | '/aura/'
    | '/api/aura/dialogue'
    | '/api/integration/cron'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses-partagees'
    | '/auth'
    | '/cockpit'
    | '/aura/methode'
    | '/aura/plateforme'
    | '/aura/science'
    | '/aura/solutions'
    | '/aura/tarifs'
    | '/avis/$token'
    | '/cockpit/abonnement'
    | '/cockpit/admin-plateforme'
    | '/cockpit/atelier'
    | '/cockpit/cas-references'
    | '/cockpit/comptes'
    | '/cockpit/demos'
    | '/cockpit/energie'
    | '/cockpit/home'
    | '/cockpit/resilience'
    | '/cockpit/studio'
    | '/cockpit/utilisateurs'
    | '/aura'
    | '/api/aura/dialogue'
    | '/api/integration/cron'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/analyses-partagees'
    | '/aura'
    | '/auth'
    | '/cockpit'
    | '/aura/methode'
    | '/aura/plateforme'
    | '/aura/science'
    | '/aura/solutions'
    | '/aura/tarifs'
    | '/avis/$token'
    | '/cockpit/abonnement'
    | '/cockpit/admin-plateforme'
    | '/cockpit/atelier'
    | '/cockpit/cas-references'
    | '/cockpit/comptes'
    | '/cockpit/demos'
    | '/cockpit/energie'
    | '/cockpit/home'
    | '/cockpit/resilience'
    | '/cockpit/studio'
    | '/cockpit/utilisateurs'
    | '/aura/'
    | '/api/aura/dialogue'
    | '/api/integration/cron'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesPartageesRoute: typeof AnalysesPartageesRoute
  AuraRoute: typeof AuraRouteWithChildren
  AuthRoute: typeof AuthRoute
  CockpitRoute: typeof CockpitRouteWithChildren
  AvisTokenRoute: typeof AvisTokenRoute
  ApiAuraDialogueRoute: typeof ApiAuraDialogueRoute
  ApiIntegrationCronRoute: typeof ApiIntegrationCronRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cockpit': {
      id: '/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof CockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura': {
      id: '/aura'
      path: '/aura'
      fullPath: '/aura'
      preLoaderRoute: typeof AuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses-partagees': {
      id: '/analyses-partagees'
      path: '/analyses-partagees'
      fullPath: '/analyses-partagees'
      preLoaderRoute: typeof AnalysesPartageesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura/': {
      id: '/aura/'
      path: '/'
      fullPath: '/aura/'
      preLoaderRoute: typeof AuraIndexRouteImport
      parentRoute: typeof AuraRoute
    }
    '/cockpit/utilisateurs': {
      id: '/cockpit/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/cockpit/utilisateurs'
      preLoaderRoute: typeof CockpitUtilisateursRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/studio': {
      id: '/cockpit/studio'
      path: '/studio'
      fullPath: '/cockpit/studio'
      preLoaderRoute: typeof CockpitStudioRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/resilience': {
      id: '/cockpit/resilience'
      path: '/resilience'
      fullPath: '/cockpit/resilience'
      preLoaderRoute: typeof CockpitResilienceRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/home': {
      id: '/cockpit/home'
      path: '/home'
      fullPath: '/cockpit/home'
      preLoaderRoute: typeof CockpitHomeRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/energie': {
      id: '/cockpit/energie'
      path: '/energie'
      fullPath: '/cockpit/energie'
      preLoaderRoute: typeof CockpitEnergieRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/demos': {
      id: '/cockpit/demos'
      path: '/demos'
      fullPath: '/cockpit/demos'
      preLoaderRoute: typeof CockpitDemosRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/comptes': {
      id: '/cockpit/comptes'
      path: '/comptes'
      fullPath: '/cockpit/comptes'
      preLoaderRoute: typeof CockpitComptesRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/cas-references': {
      id: '/cockpit/cas-references'
      path: '/cas-references'
      fullPath: '/cockpit/cas-references'
      preLoaderRoute: typeof CockpitCasReferencesRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/atelier': {
      id: '/cockpit/atelier'
      path: '/atelier'
      fullPath: '/cockpit/atelier'
      preLoaderRoute: typeof CockpitAtelierRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/admin-plateforme': {
      id: '/cockpit/admin-plateforme'
      path: '/admin-plateforme'
      fullPath: '/cockpit/admin-plateforme'
      preLoaderRoute: typeof CockpitAdminPlateformeRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/abonnement': {
      id: '/cockpit/abonnement'
      path: '/abonnement'
      fullPath: '/cockpit/abonnement'
      preLoaderRoute: typeof CockpitAbonnementRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/avis/$token': {
      id: '/avis/$token'
      path: '/avis/$token'
      fullPath: '/avis/$token'
      preLoaderRoute: typeof AvisTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura/tarifs': {
      id: '/aura/tarifs'
      path: '/tarifs'
      fullPath: '/aura/tarifs'
      preLoaderRoute: typeof AuraTarifsRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/solutions': {
      id: '/aura/solutions'
      path: '/solutions'
      fullPath: '/aura/solutions'
      preLoaderRoute: typeof AuraSolutionsRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/science': {
      id: '/aura/science'
      path: '/science'
      fullPath: '/aura/science'
      preLoaderRoute: typeof AuraScienceRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/plateforme': {
      id: '/aura/plateforme'
      path: '/plateforme'
      fullPath: '/aura/plateforme'
      preLoaderRoute: typeof AuraPlateformeRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/methode': {
      id: '/aura/methode'
      path: '/methode'
      fullPath: '/aura/methode'
      preLoaderRoute: typeof AuraMethodeRouteImport
      parentRoute: typeof AuraRoute
    }
    '/api/integration/cron': {
      id: '/api/integration/cron'
      path: '/api/integration/cron'
      fullPath: '/api/integration/cron'
      preLoaderRoute: typeof ApiIntegrationCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aura/dialogue': {
      id: '/api/aura/dialogue'
      path: '/api/aura/dialogue'
      fullPath: '/api/aura/dialogue'
      preLoaderRoute: typeof ApiAuraDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuraRouteChildren {
  AuraMethodeRoute: typeof AuraMethodeRoute
  AuraPlateformeRoute: typeof AuraPlateformeRoute
  AuraScienceRoute: typeof AuraScienceRoute
  AuraSolutionsRoute: typeof AuraSolutionsRoute
  AuraTarifsRoute: typeof AuraTarifsRoute
  AuraIndexRoute: typeof AuraIndexRoute
}

const AuraRouteChildren: AuraRouteChildren = {
  AuraMethodeRoute: AuraMethodeRoute,
  AuraPlateformeRoute: AuraPlateformeRoute,
  AuraScienceRoute: AuraScienceRoute,
  AuraSolutionsRoute: AuraSolutionsRoute,
  AuraTarifsRoute: AuraTarifsRoute,
  AuraIndexRoute: AuraIndexRoute,
}

const AuraRouteWithChildren = AuraRoute._addFileChildren(AuraRouteChildren)

interface CockpitRouteChildren {
  CockpitAbonnementRoute: typeof CockpitAbonnementRoute
  CockpitAdminPlateformeRoute: typeof CockpitAdminPlateformeRoute
  CockpitAtelierRoute: typeof CockpitAtelierRoute
  CockpitCasReferencesRoute: typeof CockpitCasReferencesRoute
  CockpitComptesRoute: typeof CockpitComptesRoute
  CockpitDemosRoute: typeof CockpitDemosRoute
  CockpitEnergieRoute: typeof CockpitEnergieRoute
  CockpitHomeRoute: typeof CockpitHomeRoute
  CockpitResilienceRoute: typeof CockpitResilienceRoute
  CockpitStudioRoute: typeof CockpitStudioRoute
  CockpitUtilisateursRoute: typeof CockpitUtilisateursRoute
}

const CockpitRouteChildren: CockpitRouteChildren = {
  CockpitAbonnementRoute: CockpitAbonnementRoute,
  CockpitAdminPlateformeRoute: CockpitAdminPlateformeRoute,
  CockpitAtelierRoute: CockpitAtelierRoute,
  CockpitCasReferencesRoute: CockpitCasReferencesRoute,
  CockpitComptesRoute: CockpitComptesRoute,
  CockpitDemosRoute: CockpitDemosRoute,
  CockpitEnergieRoute: CockpitEnergieRoute,
  CockpitHomeRoute: CockpitHomeRoute,
  CockpitResilienceRoute: CockpitResilienceRoute,
  CockpitStudioRoute: CockpitStudioRoute,
  CockpitUtilisateursRoute: CockpitUtilisateursRoute,
}

const CockpitRouteWithChildren =
  CockpitRoute._addFileChildren(CockpitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesPartageesRoute: AnalysesPartageesRoute,
  AuraRoute: AuraRouteWithChildren,
  AuthRoute: AuthRoute,
  CockpitRoute: CockpitRouteWithChildren,
  AvisTokenRoute: AvisTokenRoute,
  ApiAuraDialogueRoute: ApiAuraDialogueRoute,
  ApiIntegrationCronRoute: ApiIntegrationCronRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
